Easier debugging.

diff --git a/etc/service/dnsmasq/run b/etc/service/dnsmasq/run
--- a/etc/service/dnsmasq/run
+++ b/etc/service/dnsmasq/run
@@ -1,5 +1,7 @@
 #!/bin/bash -e
 
+trap 'echo "ERROR: $BASH_SOURCE:$LINENO $BASH_COMMAND" >&2' ERR
+
 # If internal DNS is provided by Docker, we do not run.
 if grep -q 127.0.0.11 /etc/resolv.conf ; then
   # 115 is a special exit code to signal to dinit that this program is disabling itself.
diff --git a/etc/service/dockergen/log/run b/etc/service/dockergen/log/run
--- a/etc/service/dockergen/log/run
+++ b/etc/service/dockergen/log/run
@@ -1,5 +1,7 @@
 #!/bin/bash -e
 
+trap 'echo "ERROR: $BASH_SOURCE:$LINENO $BASH_COMMAND" >&2' ERR
+
 if [ "${LOG_TO_STDOUT}" != "1" ]; then
   mkdir -p /var/log/dockergen
   chown nobody:nogroup /var/log/dockergen
